defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local

# snapshot
save_snapshot: True
load_snap: "/home/davis/.vip/resnet50/model.pt"

# replay buffer
num_workers: 10
batch_size: 8
train_steps: 2000000
eval_freq: 10000

# misc
seed: 1
device: cuda

# experiment
experiment: feat_tcc_1203_drawer-open-random
wandbuser: 
wandbproject: vip_finetune

# data
dataset: "drawer-open-random"
datapath: "/tmp2/davis/sawyer/drawer-open-random"
doaug: "none"

agent:
  _target_: vip.VIP
  device: ${device}
  lr: 1e-4
  hidden_dim: 1024
  size: 50
  l2weight: 0.001
  l1weight: 0.001
  num_negatives: 3


# tcc loss
tcc: true
feat_tcc: true
reward_tcc: false
tcc_loss_type: "regression"
